title: Blog Bloggety Blog McBlog

author: Steven Bakker
email: sb@monkey-mind.net
description: > # this means to ignore newlines until "baseurl:"
  Blog of Steven Bakker, mostly related to software development and
  related technology... Nowadays, I mostly code in Perl and Bash.

# social links
twitter_username: apekool404 # DO NOT include the @ character, or else the build will fail!
github_username:  sbakker # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage

theme: minima
minima:
  skin: dark
  
